### ISSUE TITLE
communicate disk and memory usage during a build

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-build-container#237]
#### User Story

A user should be able to determine their disk/memory usage to help optimize their site builds.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] specify available disk and memory in the build log before the clone/script/build process
- [ ] disk and memory appear in the build log
- [ ] Change made live via federalist-garden-build

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by drewbo** [comment]
Wanted to do a rough outline of disk/memory monitoring implementation concepts before we start building anything here. Our builds are run using `cf tasks` which reserve a [certain amount of memory and disk space](https://github.com/cloud-gov/pages-builder/blob/staging/.cloudgov/manifest.yml). Cloud Foundry creates a container specifically for each task.
1. In theory, metrics could be monitored from outside the container, either via a Cloud Foundry API, or `docker stat` but I don't think Cloud Foundry exposes this information and the docker commands will be difficult to run remotely on ephemeral containers
2. Within the container, we could run monitoring with a variety of tools (`ps`, `top`, or python specific libraries like `psutil`), the question is whether these commands run as a wrapper around the current build script, or are added directly to the build script. The former is cleaner (separation of concerns) but harder to implement initially because it changes the docker command. The latter is likely easier to implement but more likely to increase technical debt and potential bugs as it gets too tightly coupled to the build script. One potential compromise is adding monitoring to the build script but at the "highest" level possible (i.e. wrapping the top-level build command from within the python script).

My recommendation is to investigate the final compromise solution which tracks CPU/MEM usage within the python script but implemented within `main.py`

**Comment by svenaas** [comment]
My first thought is that this issue has been waiting its turn for more than thirty months and we can probably afford to take the time to do it in a way that limits the increase in technical debt, and separating concerns would help make the eventual solution easier to maintain and verify.

That said, I think the compromise you suggest sounds reasonable and pragmatic.

**Comment by apburnes** [comment]
Do we want reassess the issue's acceptance criteria for the metrics to just stdout in the build log or do we want to save them somewhere else?

If we just want to stdout metrics to the build logs, going down the second option with your recommendation makes sense to me.

If we want to save the metrics in the database or somewhere else, CF API does have process metrics for apps. The docs for the [processes](http://v3-apidocs.cloudfoundry.org/version/3.130.0/index.html#processes) and the [app usage events](http://v3-apidocs.cloudfoundry.org/version/3.130.0/index.html#app-usage-events) may be useful to look at. Also the [CF top plugin](https://github.com/ECSTeam/cloudfoundry-top-plugin) provides similar functionality that could provide inspiration.

**Comment by drewbo** [comment]
👍 I think to start we should keep to it stdout metrics in the build logs. I'm interested in the latter option eventually but wasn't sure that the CF API can show memory/cpu usage (rather than reservation) for tasks. I will checkout the top plugin since that might fit the bill for future monitoring uses
