### ISSUE TITLE
Explore setting environment variable `NODE_ENV=production` for all site builds

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-build-container#424]
Standard production environments for node.js based applications and builds set the environment variable `NODE_ENV=production`. Currently, the build container is not setting this by default. Explore the options of setting this environment variable.

## Notes

- Explore the possible side effects from setting `NODE_ENV=production` by default
- Are there any current sites setting their own `NODE_ENV` variable and are they not set to `production`

## Acceptance Criteria

- [ ] Investigate if it is OK to set the default env var `NODE_ENV=production`
- [ ] If all signs point to yes, add `NODE_ENV=production` to the build container environment
- [ ] Allow user set `NODE_ENV` value to override the default `production`

**Comment by aduth** [comment]
> * Explore the possible side effects from setting `NODE_ENV=production` by default

At least one is that `npm install` will skip `devDependencies`. I was going to suggest considering tying `npm install --production` with any changes to `NODE_ENV` default, since if the idea is to assume that Pages builds for production, presumably that would extend to dependencies as well.

>With the `--production` flag (or when the `NODE_ENV` environment variable is set to `production`), npm will not install modules listed in `devDependencies`. 

https://docs.npmjs.com/cli/v8/commands/npm-install

This might have some more downstream impact if projects assume that `devDependencies` are installed. It could be possible to change the `NODE_ENV` default while still installing `devDependencies`, essentially the equivalent of `NODE_ENV=production npm install --production=false`.

**Comment by apburnes** [comment]
Closing due to other priorities.
